== Groovy Features

[%build]
* Simple Syntax (Less Noise)
* Scripting Support
* Operator Overloading
* Meta-Programming

== Simple Syntax

[source,groovy]
.Maps and lists
----
def map = [language: 'Groovy']
def list = ['foo', 'bar']
----

== Simple Syntax

[source,groovy]
.Command chaining and optional parenthesis
----
say hello to 'Craig'

// say(hello).to('Craig')
----

== Simple Syntax

[source,groovy]
.Named arguments
----
class Note {
  static from(Map args, String name) {
    println "${name} said ${args.message}"
  }
}

Note.from 'Craig Burke', message: 'Hey, how are you?'
----

== Scripting Support

[source,java]
.Java code to print a String
----
public class ScriptClass {

  public static void main(String[] args) {
    System.out.println("Hello World");
  }

}
----

[source,groovy]
.Equivalent Groovy Code
----
println 'Hello World'
----

== Operator Overloading

[.operators,width=50]
|===

| a + b       | a.plus(b)

| a - b       | a.minus(b)

| a * b       | a.multiply(b)

| a ** b      | a.power(b)

| a / b       | a.div(b)

| a % b       | a.mod(b) 

| a \| b       | a.or(b)

| a & b       | a.and(b)

| a ^ b       | a.xor(b)

| a++ or ++a  | a.next()

| a-- or --a  | a.previous()

| a << b      | a.leftShift(b)

| a >> b      | a.rightShift(b)

| a <=> b     | a.compareTo(b)

|===

[%build]
== Getters and Setters

[source,groovy]
----
class Person {
  String name
}
Person person = new Person()
----

[source,groovy]
----
person.name = 'Craig'
// person.setName('Craig')
----

[source,groovy]
----
println person.name
// println person.getName()
----

[source,groovy]
----
person.nickName = person.name
// person.setNickName(person.getName())
----
 
== Dynamic Properties

[source,groovy]
.Extending the Number class
----
Number.metaClass.getDollars = { delegate as BigDecimal }

Number.metaClass.getProperty = { String name ->
  def rates = [euros: 1.1f, pesos: 0.063f]
  delegate * (rates[name] as BigDecimal)
}
----

[source,groovy]
.Adding different currencies together
----
def total = 20.dollars + 40.euros + 200.pesos
assert total == 76.60
----

== Dynamic Methods

[source,groovy]
----
class Person {
  def methodMissing(String name, args) {
    if (name.startsWith('say')) {
      String message = (name - 'say').trim()
      println message
    }
  }
}
----

[source,groovy]
.Trying out our dynamic method
----
Person you = new Person()
you.sayHello()
you."say Craig is Awesome"()
----

== Closure Delegation

[source,groovy]
.Defining a simple closure
----
Closure myClosure = {
  name = 'Craig'
  printName()
}
----

[source,groovy]
.Methods and properties set to resolve to a NamePrinter object
----
class NamePrinter {
  String name

  void printName() {
    println "My Name is ${name}!!!"
  }
}

myClosure.delegate = new NamePrinter()
myClosure.resolveStrategy = Closure.DELEGATE_FIRST
myClosure()
----


